name: IntegrationTest
on:
  workflow_call:
    inputs:
      VERSION:
        required: true
        type: string
jobs:
  test:
    name: Run integrations tests
    runs-on: [self-hosted, genin]
    steps:
      - name: dummy
        run: echo "hello"

