name: Release
on:
  workflow_call:
    inputs:
      VERSION:
        required: true
        type: string
    secrets:
      DEPLOY_PROD_SSH_KEY:
        description: 'A DEPLOY_PROD_SSH_KEY passed from UnitTest'
        required: true
      KNOWN_HOSTS:
        description: 'A KNOWN_HOSTS passed from UnitTest'
        required: true
env:
  VERSION: ${{ inputs.version }}
  YUM_REGISTRY: https://binary.picodata.io/repository/yum
  DEB_REGISTRY: https://binary.picodata.io/repository/ubuntu
  RAW_REGISTRY: https://binary.picodata.io/repository/raw
jobs:
  publish:
    name: Publish to download.picodata.io
    runs-on: [ self-hosted, genin ]
    steps:
      - name: Download centos7 rpm
        uses: actions/download-artifact@v3
        with:
          name: genin-${{ env.VERSION }}-1.el7.x86_64.rpm
          path: ./centos7/
      - name: Download centos8 rpm
        uses: actions/download-artifact@v3
        with:
          name: genin-${{ env.VERSION }}-1.el8.x86_64.rpm
          path: ./centos8/
      - name: Download deb package
        uses: actions/download-artifact@v3
        with:
          name: genin-${{ env.VERSION }}.amd64.deb
          path: ./debian/
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DEPLOY_PROD_SSH_KEY }}
          name: id_rsa
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
          if_key_exists: replace
      - name: Upload centos7 rpm to picodata
        run: |
          scp -o stricthostkeychecking=no centos7/genin-${{ env.VERSION }}-1.el7.x86_64.rpm  ansible@94.26.239.246:/data/nginx/www/packrepo/tarantool-picodata/el/7/x86_64/
          ssh -o stricthostkeychecking=no ansible@94.26.239.246 "cd /data/nginx/www/packrepo/tarantool-picodata/el/7/ && createrepo --update x86_64 && gpg --no-tty --yes -u kdy@picodata.io --detach-sign --armor x86_64/repodata/repomd.xml"
      - name: Upload centos8 rpm to picodata
        run: |
          scp -o stricthostkeychecking=no centos8/genin-${{ env.VERSION }}-1.el8.x86_64.rpm  ansible@94.26.239.246:/data/nginx/www/packrepo/tarantool-picodata/el/8/x86_64/
          ssh -o stricthostkeychecking=no ansible@94.26.239.246 "cd /data/nginx/www/packrepo/tarantool-picodata/el/8/ && createrepo --update x86_64 && gpg --no-tty --yes -u kdy@picodata.io --detach-sign --armor x86_64/repodata/repomd.xml"
      - name: Upload deb to picodata
        run: |
          ssh -o stricthostkeychecking=no ansible@94.26.239.246 "mkdir -p ~/.deb"
          scp -o stricthostkeychecking=no debian/genin-${{ env.VERSION }}.amd64.deb ansible@94.26.239.246:.deb/
          ssh -o stricthostkeychecking=no ansible@94.26.239.246 "reprepro -b /data/nginx/www/packrepo/tarantool-picodata/ubuntu/ -C main includedeb focal ~/.deb/genin-${{ env.VERSION }}.amd64.deb; rm ~/.deb/genin-${{ env.VERSION }}.amd64.deb"

  release:
    name: Create new release
    runs-on: [ self-hosted, genin ]
    needs: [ publish ]
    steps:
      - name: Create genin Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.VERSION }}
          release_name: genin v${{ env.VERSION }}
          body: |
            ---
            - [genin v${{ env.VERSION }}](#genin-v${{ env.VERSION }})
              * [executable](#executable)
              * [MacOSX](#macosx)
              * [Centos x86_64](#centos-x86_64)
              * [Debian x86_64](#debian-x86_64)
            
            ### Executable
            [genin-${{ env.VERSION }}-x86_64-musl.tar.gz](${{ env.RAW_REGISTRY }}/genin/bin/genin-${{ env.VERSION }}-x86_64-musl.tar.gz)
            
            ### MacOSX
            [genin-${{ env.VERSION }}-x86_64-macos.tar.gz](${{ env.RAW_REGISTRY }}/genin/osx/genin-${{ env.VERSION }}-x86_64-macosx.tar.gz)
            
            ### Centos x86_64:
            [genin-${{ env.VERSION }}-1.el7.x86_64.rpm](${{ env.YUM_REGISTRY }}/el/7/x86_64/os/genin-${{ env.VERSION }}-1.el7.x86_64.rpm)
            [genin-${{ env.VERSION }}-1.el8.x86_64.rpm](${{ env.YUM_REGISTRY }}/el/8/x86_64/os/genin-${{ env.VERSION }}-1.el8.x86_64.rpm)

            ### Debian x86_64
            [genin-${{ env.VERSION }}.amd64.deb](${{ env.RAW_REGISTRY }}/genin/deb/genin-${{ env.VERSION }}.amd64.deb)


